// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/book.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book_BookType int32

const (
	Book_SCIENCE    Book_BookType = 0
	Book_LITERATURE Book_BookType = 1
)

var Book_BookType_name = map[int32]string{
	0: "SCIENCE",
	1: "LITERATURE",
}

var Book_BookType_value = map[string]int32{
	"SCIENCE":    0,
	"LITERATURE": 1,
}

func (x Book_BookType) String() string {
	return proto.EnumName(Book_BookType_name, int32(x))
}

func (Book_BookType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{1, 0}
}

type Publisher struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Publisher) Reset()         { *m = Publisher{} }
func (m *Publisher) String() string { return proto.CompactTextString(m) }
func (*Publisher) ProtoMessage()    {}
func (*Publisher) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{0}
}

func (m *Publisher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Publisher.Unmarshal(m, b)
}
func (m *Publisher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Publisher.Marshal(b, m, deterministic)
}
func (m *Publisher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Publisher.Merge(m, src)
}
func (m *Publisher) XXX_Size() int {
	return xxx_messageInfo_Publisher.Size(m)
}
func (m *Publisher) XXX_DiscardUnknown() {
	xxx_messageInfo_Publisher.DiscardUnknown(m)
}

var xxx_messageInfo_Publisher proto.InternalMessageInfo

func (m *Publisher) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Book struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author               *Book_Author  `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Type                 Book_BookType `protobuf:"varint,3,opt,name=type,proto3,enum=proto.Book_BookType" json:"type,omitempty"`
	Publisher            *Publisher    `protobuf:"bytes,4,opt,name=publisher,proto3" json:"publisher,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{1}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Book) GetAuthor() *Book_Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Book) GetType() Book_BookType {
	if m != nil {
		return m.Type
	}
	return Book_SCIENCE
}

func (m *Book) GetPublisher() *Publisher {
	if m != nil {
		return m.Publisher
	}
	return nil
}

type Book_Author struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book_Author) Reset()         { *m = Book_Author{} }
func (m *Book_Author) String() string { return proto.CompactTextString(m) }
func (*Book_Author) ProtoMessage()    {}
func (*Book_Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{1, 0}
}

func (m *Book_Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book_Author.Unmarshal(m, b)
}
func (m *Book_Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book_Author.Marshal(b, m, deterministic)
}
func (m *Book_Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book_Author.Merge(m, src)
}
func (m *Book_Author) XXX_Size() int {
	return xxx_messageInfo_Book_Author.Size(m)
}
func (m *Book_Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Book_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Book_Author proto.InternalMessageInfo

func (m *Book_Author) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Book_Author) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.Book_BookType", Book_BookType_name, Book_BookType_value)
	proto.RegisterType((*Publisher)(nil), "proto.Publisher")
	proto.RegisterType((*Book)(nil), "proto.Book")
	proto.RegisterType((*Book_Author)(nil), "proto.Book.Author")
}

func init() {
	proto.RegisterFile("proto/book.proto", fileDescriptor_eff6d7530e9d9699)
}

var fileDescriptor_eff6d7530e9d9699 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xca, 0xcf, 0xcf, 0xd6, 0x03, 0x33, 0x85, 0x58, 0xc1, 0x94, 0x92, 0x3c, 0x17,
	0x67, 0x40, 0x69, 0x52, 0x4e, 0x66, 0x71, 0x46, 0x6a, 0x91, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62,
	0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0xad, 0xd4, 0xc8, 0xc4, 0xc5, 0xe2,
	0x94, 0x9f, 0x9f, 0x8d, 0x4d, 0x52, 0x48, 0x8b, 0x8b, 0x2d, 0xb1, 0xb4, 0x24, 0x23, 0xbf, 0x48,
	0x82, 0x49, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x08, 0x62, 0xb8, 0x1e, 0x48, 0x83, 0x9e, 0x23, 0x58,
	0x26, 0x08, 0xaa, 0x42, 0x48, 0x83, 0x8b, 0xa5, 0xa4, 0xb2, 0x20, 0x55, 0x82, 0x59, 0x81, 0x51,
	0x83, 0xcf, 0x48, 0x04, 0x59, 0x25, 0x88, 0x08, 0xa9, 0x2c, 0x48, 0x0d, 0x02, 0xab, 0x10, 0xd2,
	0xe3, 0xe2, 0x2c, 0x80, 0xb9, 0x49, 0x82, 0x05, 0x6c, 0xb0, 0x00, 0x54, 0x39, 0xdc, 0xad, 0x41,
	0x08, 0x25, 0x52, 0x66, 0x5c, 0x6c, 0x10, 0xbb, 0xb0, 0xba, 0x51, 0x82, 0x8b, 0x3d, 0x31, 0x25,
	0xa5, 0x28, 0xb5, 0xb8, 0x18, 0xec, 0x48, 0xce, 0x20, 0x18, 0x57, 0x49, 0x9d, 0x8b, 0x03, 0x66,
	0xb3, 0x10, 0x37, 0x17, 0x7b, 0xb0, 0xb3, 0xa7, 0xab, 0x9f, 0xb3, 0xab, 0x00, 0x83, 0x10, 0x1f,
	0x17, 0x97, 0x8f, 0x67, 0x88, 0x6b, 0x90, 0x63, 0x48, 0x68, 0x90, 0xab, 0x00, 0x63, 0x12, 0x1b,
	0xd8, 0x72, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xf3, 0xc1, 0x4b, 0x46, 0x01, 0x00,
	0x00,
}
